### ISSUE TITLE
How do I get contract from dependency?

### ISSUE THREAD

**Issue by j4ckcyw** [wighawag/hardhat-deploy-ethers#11]
Let's say I want to write a script that reads yieldyak's [smart contact](https://github.com/yieldyak/smart-contracts). When I do `await ethers.getContractFactory("DexStrategyV4")`, hardhat complains that `Artifacts was not found`. Is there a way for getContractFactory to resolve name in node_modules?

**Comment by wighawag** [comment]
see : https://github.com/nomiclabs/hardhat/issues/1040

**Comment by wighawag** [comment]
hardhat-deploy-ethers@next has been released
Please, try it out.

It is now an extension to hardhat-ethers so you need both

But note that that new version do not support external artifact if you were using them

**Comment by wighawag** [comment]
closing as 0.4.1 is now out as main release
