### ISSUE TITLE
Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy-ethers#18]
I have the following code:
```typescript
/* eslint-disable node/no-missing-import */
// eslint-disable-next-line node/no-unpublished-import
import { HardhatRuntimeEnvironment } from "hardhat/types"
import { DeployFunction } from "hardhat-deploy/types"
import { networkConfig } from "../helper-hardhat-config"

const deployAPIConsumer: DeployFunction = async function (
  hre: HardhatRuntimeEnvironment
) {
  const { deployments, getNamedAccounts, getChainId } = hre
.
.
.
```

And Im running into the following linting error:
```
Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)
```
My hardhat.config.ts looks like:

```typescript
import * as dotenv from "dotenv"

import { HardhatUserConfig, task } from "hardhat/config"
import "@nomiclabs/hardhat-etherscan"
import "@nomiclabs/hardhat-waffle"
import "@typechain/hardhat"
import "hardhat-gas-reporter"
import "solidity-coverage"
import "hardhat-deploy"
import "@appliedblockchain/chainlink-plugins-fund-link"
import "hardhat-deploy-ethers"

dotenv.config()
```

However, my code runs fine. Is this an error with VSCode or the plugin I'm using?

**Comment by pfives** [comment]
@PatrickAlphaC Hey did you ever figure this out? I'm getting the exact same error

**Comment by PatrickAlphaC** [comment]
Not sure how I fixed it :/

I ended up redoing everything from scratch and I didn't get the error the second time.

**Comment by dibakarsutradhar** [comment]
I have recently encountered the same issue in my hardhat project. In my case, the problem was, that I was importing `{ HardhatUserConfig }` from `'hardhat/type' instead of 'hardhat/config' in the hardhat.config file.
Changing `type` to 'config' fixed the issue.
Hope this helps.

**Comment by wighawag** [comment]
hardhat-deploy-ethers@next has been released
Please, try it out.

It is now an extension to hardhat-ethers so you need both

But note that that new version do not support external artifact if you were using them
