### ISSUE TITLE
Latest hardhat-deploy-ethers 0.3.0-beta.11 not tagged on git

### ISSUE THREAD

**Issue by Magicking** [wighawag/hardhat-deploy-ethers#19]
It seems that the latest is not tagged on the git repository but present at https://www.npmjs.com/package/hardhat-deploy-ethers/v/0.3.0-beta.11

**Comment by wighawag** [comment]
Yes seems to have not been tagged, there is a commit there : https://github.com/wighawag/hardhat-deploy-ethers/commit/dc87dcab772f7bbd3399ad4393801fb7f629845e
