### ISSUE TITLE
Installation advice breaks yarn outdated

### ISSUE THREAD

**Issue by aspiers** [wighawag/hardhat-deploy-ethers#24]
If I have this in my `devDependencies`:

        "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers",

or this:

        "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.12",

then when I run `yarn outdated`, I get:

```
yarn outdated v1.22.15
error Couldn't find any versions for "@nomiclabs/hardhat-ethers" that matches "^0.3.0-beta.12"
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**Comment by KholdStare** [comment]
I have the same issue. Makes hardhat-deploy unusable for me.

**Comment by aalmada** [comment]
Any news on making `hardhat-deploy-ethers` as an extension of `@nomiclabs/hardhat-ethers`. That would simplify so much both installation and maintenance.
By the way, thank you so much for making `hardhat-deploy` such a great plugin.

**Comment by wighawag** [comment]
hardhat-deploy-ethers@next has been released
Please, try it out.

It is now an extension to hardhat-ethers so you need both

But note that that new version do not support external artifact if you were using them
