### ISSUE TITLE
unmet peer dependencies with hardhat-chai-matchers & hardhat-toolbox (pnpm)

### ISSUE THREAD

**Issue by wottpal** [wighawag/hardhat-deploy-ethers#28]
hey! i installed `hardhat-deploy-ethers` the recommended way with pnpm but i get the following warnings:

```
WARN  Issues with peer dependencies found

packages/hardhat
├─┬ @nomicfoundation/hardhat-chai-matchers
│ └── ✕ unmet peer @nomiclabs/hardhat-ethers@^2.0.0: found 0.3.0-beta.13
├─┬ @nomicfoundation/hardhat-toolbox
  └── ✕ unmet peer @nomiclabs/hardhat-ethers@^2.0.0: found 0.3.0-beta.13
```

how to fix those?

**Comment by wighawag** [comment]
hardhat-deploy-ethers@next has been released
Please, try it out.

It is now an extension to hardhat-ethers so you need both

But note that that new version do not support external artifact if you were using them
