### ISSUE TITLE
Why still keep this as fork of hardhat-ethers?

### ISSUE THREAD

**Issue by aalmada** [wighawag/hardhat-deploy-ethers#34]
Hi! 
First I'd like to thank you for developing and maintaining `hardhat-deploy`. It's a great addition to `hardhat`. 
There's one thing that has been an annoyance but I've always wondered when it would become a problem. `hardhat-deploy-ethers` is still a fork of `hardhat-ethers`. The [last release of this fork has been 1 year ago](https://www.npmjs.com/package/hardhat-deploy-ethers?activeTab=versions) while the [latest update of the original was 9 days ago](https://www.npmjs.com/package/@nomiclabs/hardhat-ethers?activeTab=versions).
Do you still plan to make this a plugin or maybe merge the added features to `hardhat-ethers`? I'm sure it would also save you time not having to maintain and have to answer issues here.

**Comment by wighawag** [comment]
HI @aalmada hardhat-deploy-ethers@next has been released
You can try it out, it is now an extension to hardhat-ethers so you need both
Note though that that new version do not support external artifact if you were using them

**Comment by n00b21337** [comment]
> hardhat-deploy-ethers@next

can you help us find it? I checked tags, checked branches, checked NPM wherever I search for I cant find 
hardhat-deploy-ethers@next
