### ISSUE TITLE
TypeError: hardhat_1.ethers.getContract is not a function

### ISSUE THREAD

**Issue by gigamesh** [wighawag/hardhat-deploy-ethers#5]
Hi - love all your work! It has been really helpful. 

I just tried migrating from buidler, and I'm pretty sure I have everything set up correctly in the config, but I'm getting this error:

`TypeError: hardhat_1.ethers.getContract is not a function`

...`ethers` exists, but `getContract` doesn't. 

package.json dev dependencies:
```
  "devDependencies": {
    "@ethereum-waffle/chai": "^3.0.2",
    "@ethersproject/bignumber": "^5.0.5",
    "@ethersproject/bytes": "^5.0.3",
    "@ethersproject/solidity": "^5.0.2",
    "@ethersproject/wallet": "^5.0.2",
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@types/chai": "^4.2.11",
    "@types/mocha": "^8.0.2",
    "@types/node": "^14.10.2",
    "chai": "^4.2.0",
    "creaton-common": "../common-lib",
    "cross-env": "^7.0.2",
    "dotenv": "^8.2.0",
    "ethers": "^5.0.19",
    "hardhat": "^2.0.2",
    "hardhat-deploy": "^0.7.0-beta.18",
    "hardhat-deploy-ethers": "^0.3.0-beta.5",
    "mocha": "^8.1.1",
    "solidity-coverage": "^0.7.10",
    "ts-node": "^9.0.0",
    "typescript": "^3.8.3"
  },
```

imports in hardhat.config.ts:
```
import 'dotenv';
import 'hardhat/config';
import 'hardhat-deploy';
import 'hardhat-deploy-ethers';
import '@nomiclabs/hardhat-ethers';
```

Any ideas?

**Comment by wighawag** [comment]
The dependencies indicate that you do not have any of the plugin installed. 
Can you provide a more complete example

You can also see here an example project that got both hardhat-deploy and hardhat-deploy-ethers used : https://github.com/wighawag/template-ethereum-contracts

**Comment by gigamesh** [comment]
same result - I also tried wiping node_modules, package-lock.json, and reinstalled

**Comment by wighawag** [comment]
oh, I see, I did not spotted first time
you are using both `import '@nomiclabs/hardhat-ethers';` and `import 'hardhat-deploy-ethers`
you need to use only `import 'hardhat-deploy-ethers`

**Comment by gigamesh** [comment]
that did the trick - thank you!
